import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex flex-wrap gap-3 justify-center py-4 bg-slate-800">
          <Link
            href="/wr"
            className="bg-green-500 hover:bg-green-700 px-5 py-2 text-sm leading-5 rounded-full font-semibold text-white"
          >
            Wellreceived
          </Link>
          <Link
            href="/sfca"
            className="bg-black hover:bg-slate-900 px-5 py-2 text-sm leading-5 rounded-full font-semibold text-white"
          >
            Serviceforge CA
          </Link>
          <Link
            href="#"
            className="bg-gray-500 hover:bg-gray-700 px-5 py-2 text-sm leading-5 rounded-full font-semibold text-white"
          >
            Answerconnect US - WIP 🛠️
          </Link>
          <Link
            href="#"
            className="bg-gray-500 hover:bg-gray-700 px-5 py-2 text-sm leading-5 rounded-full font-semibold text-white"
          >
            Answerconnect UK - WIP 🛠️
          </Link>
          <Link
            href="#"
            className="bg-gray-500 hover:bg-gray-700 px-5 py-2 text-sm leading-5 rounded-full font-semibold text-white"
          >
            Answerforce US - WIP 🛠️
          </Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
